// starter-apps/vue/vue-template/src/views/About/AboutTopic.vue
<script lang="ts" setup>
import { useI18n } from 'vue-i18n'
import Heading from '@/components/Heading.vue'
import Text from '@/components/Text.vue'
import DateModified from '@/components/DateModified.vue'

const { t } = useI18n()
</script>
<template>
  <Heading tag="h1">{{ t('aboutPage.aboutTopic.heading') }}</Heading>
  <Text>{{ t('aboutPage.aboutTopic.intro') }}</Text>
  <DateModified date="2024-09-10"></DateModified>
</template>

// starter-apps/react/react-template/src/pages/AboutTopic.tsx
import { useTranslation } from 'react-i18next'
import { GcdsDateModified, GcdsHeading, GcdsText } from '@gcds-core/components-react'

export default function AboutTopicPage() {
  const { t } = useTranslation()

  return (
    <>
      <GcdsHeading tag="h1">{t('aboutPage.aboutTopic.heading')}</GcdsHeading>
      <GcdsText>{t('aboutPage.aboutTopic.intro')}</GcdsText>
      <GcdsDateModified>2024-09-10</GcdsDateModified>
    </>
  )
}
