// starter-apps/vue/vue-template/src/views/Home.vue
<script setup>
import { useI18n } from 'vue-i18n'
import Heading from '@/components/Heading.vue'
import Text from '@/components/Text.vue'
import DateModified from '@/components/DateModified.vue'

const { t } = useI18n()
</script>
<template>
  <div>
    <section>
      <Heading tag="h1">{{ t('homePage.heading') }}</Heading>
      <Text>
        {{ t('homePage.paragraph') }}
      </Text>
      <Text>
        {{ t('homePage.paragraph2') }}
      </Text>
      <Text>
        {{ t('homePage.paragraph3') }}
      </Text>
    </section>
    <DateModified date="2024-09-10"></DateModified>
  </div>
</template>

// starter-apps/react/react-template/src/pages/Home.tsx
import { useTranslation } from 'react-i18next'
import { GcdsDateModified, GcdsHeading, GcdsText } from '@gcds-core/components-react'

export default function HomePage() {
  const { t } = useTranslation()

  return (
    <>
      <section>
        <GcdsHeading tag="h1">{t('homePage.heading')}</GcdsHeading>
        <GcdsText>{t('homePage.paragraph')}</GcdsText>
        <GcdsText>{t('homePage.paragraph2')}</GcdsText>
        <GcdsText>{t('homePage.paragraph3')}</GcdsText>
      </section>
      <GcdsDateModified>2024-09-10</GcdsDateModified>
    </>
  )
}
