// starter-apps/vue/vue-template/src/components/forms/Radios.vue
<script setup>
const { id, name, options, required, hint, legend, validateOn, validator } = defineProps([
  'id',
  'name',
  'options',
  'required',
  'hint',
  'legend',
  'validateOn',
  'validator'
])
const model = defineModel()
</script>
<template>
  <gcds-radios
    v-model="model"
    :options="options"
    :hint="hint"
    :id="id"
    :name="name"
    :legend="legend"
    :required="required"
    :validate-on="validateOn"
    :validator="validator"
  ></gcds-radios>
</template>

// fable-test-app/src/components/Radios.tsx
import React from 'react';
import { GcdsRadios } from "@cdssnc/gcds-components-react";

type RadioObject = {
  id: string;
  label: string;
  value: string;
  hint?: string;
  checked?: boolean;
};

interface RadiosProps {
  hint?: string;
  legend: string;
  name: string;
  onInput?: (e: any) => void;
  value?: string;
  validateOn?: "blur" | "submit" | "other";
  required?: boolean;
  className?: string;
  options: string | RadioObject[];
}

const Radios: React.FC<RadiosProps> = React.memo(({
  hint,
  legend,
  name,
  onInput,
  validateOn,
  required,
  value,
  className,
  options
}) => (
  <GcdsRadios
    legend={legend}
    hint={hint}
    name={name}
    options={options}
    value={value}
    validateOn={validateOn}
    onInput={onInput}
    required={required}
    className={className}
  ></GcdsRadios>
));

export default Radios;
