// starter-apps/react/react-template/src/pages/About.tsx
import { useTranslation } from 'react-i18next'
import { useParams } from 'react-router-dom'
import { GcdsDateModified, GcdsHeading, GcdsText } from '@gcds-core/components-react'

import AppLink from '@/components/AppLink'
import { defaultLocale } from '@/routing/constants'
import { getLocalizedPath, isAppLocale } from '@/routing/localizedRoutes'

export default function AboutPage() {
  const { t } = useTranslation()
  const { locale: localeParam } = useParams()
  const locale = isAppLocale(localeParam) ? localeParam : defaultLocale

  return (
    <>
      <section>
          <GcdsHeading tag="h1">{t('aboutPage.heading')}</GcdsHeading>
      <GcdsText>{t('aboutPage.intro')}</GcdsText>
      <section>
        <AppLink to={getLocalizedPath('aboutTopic', locale)}>
          {t('aboutPage.aboutTopic.heading')}
        </AppLink>
      </section>
      <GcdsDateModified>2024-09-10</GcdsDateModified>
    </>
  )
}

// starter-apps/vue/vue-template/src/views/About/About.vue
<script lang="ts" setup>
import AppLink from '@/components/AppLink.vue'
import { getLocalizedPath } from '@/router'
import { useI18n } from 'vue-i18n'
import Text from '@/components/Text.vue'
import Heading from '@/components/Heading.vue'
import DateModified from '@/components/DateModified.vue'

const { t } = useI18n()
</script>
<template>
  <div class="about">
    <Heading tag="h1">{{ t('aboutPage.heading') }}</Heading>
    <Text>
      {{ t('aboutPage.intro') }}
    </Text>
    <section>
      <AppLink :to="getLocalizedPath('about/topic')">{{
        t('aboutPage.aboutTopic.heading')
      }}</AppLink>
    </section>
    <DateModified date="2024-09-10"></DateModified>
  </div>
</template>

<style scoped></style>
