// starter-apps/react/react-template/src/pages/NotFound.tsx
import { useTranslation } from 'react-i18next'
import { GcdsDateModified, GcdsHeading, GcdsText } from '@gcds-core/components-react'

export default function NotFoundPage() {
  const { t } = useTranslation()

  return (
    <>
      <GcdsHeading tag="h1">{t('notFoundPage.heading')}</GcdsHeading>
      <GcdsText>{t('notFoundPage.intro')}</GcdsText>
      <GcdsDateModified>2024-09-10</GcdsDateModified>
    </>
  )
}

// starter-apps/vue/vue-template/src/views/NotFound.vue
<script setup>
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>
<template>
  <div class="not-found">
    <gcds-heading class="mb-400" tag="h1">{{ t('notFoundPage.heading') }}</gcds-heading>
    <gcds-text>
      {{ t('notFoundPage.intro') }}
    </gcds-text>
  </div>
</template>
