// starter-apps/react/react-template/src/pages/ReportABug.tsx
import { useState } from 'react'
import type { FormEvent } from 'react'
import { useTranslation } from 'react-i18next'
import {
  GcdsButton,
  GcdsDateModified,
  GcdsErrorSummary,
  GcdsHeading,
  GcdsInput,
  GcdsText,
  GcdsTextarea
} from '@gcds-core/components-react'

import type { ReportBugFormData } from '@/types/report'
import { initialReportBugFormData } from '@/types/report'
import { buildGithubIssueUrl } from '@/utils/githubIssue'

function setField(
  previous: ReportBugFormData,
  fieldName: keyof ReportBugFormData,
  value: string
): ReportBugFormData {
  return {
    ...previous,
    [fieldName]: value
  }
}

export default function ReportABugPage() {
  const { t } = useTranslation()
  const [formData, setFormData] = useState<ReportBugFormData>(initialReportBugFormData)
  const [submitted, setSubmitted] = useState(false)

  const handleInputChange = (event: CustomEvent) => {
    const target = event.target as HTMLInputElement | HTMLTextAreaElement
    const fieldName = target.name as keyof ReportBugFormData

    if (!fieldName) {
      return
    }

    setFormData((previous) => setField(previous, fieldName, target.value))
  }

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    const form = event.currentTarget
    if (!form.checkValidity()) {
      return
    }

    setSubmitted(true)
  }

  return (
    <>
      <section>
        <GcdsHeading tag="h1">{t('reportABugPage.heading')}</GcdsHeading>
        <GcdsText>{t('reportABugPage.intro')}</GcdsText>
      </section>

      {!submitted ? (
        <form name="bugReportForm" noValidate onSubmit={handleSubmit}>
          <GcdsErrorSummary listen />

          {/* TODO: This form is a starter template.
              Add/remove fields to match your issue workflow and keep name/inputId/textareaId stable for tests. */}
          <GcdsInput
            hint={t('reportABugPage.form.versionNumberHint')}
            inputId="version"
            label={t('reportABugPage.form.versionNumber')}
            name="version"
            onGcdsInput={handleInputChange}
            required
            validateOn="submit"
            value={formData.version}
          />
          <GcdsInput
            hint={t('reportABugPage.form.titleHint')}
            inputId="title"
            label={t('reportABugPage.form.title')}
            name="title"
            onGcdsInput={handleInputChange}
            required
            validateOn="submit"
            value={formData.title}
          />
          <GcdsTextarea
            hint={t('reportABugPage.form.currentBehaviorHint')}
            label={t('reportABugPage.form.currentBehavior')}
            name="currentBehavior"
            onGcdsInput={handleInputChange}
            textareaId="currentBehavior"
            validateOn="submit"
            value={formData.currentBehavior}
          />
          <GcdsTextarea
            hint={t('reportABugPage.form.expectedBehaviorHint')}
            label={t('reportABugPage.form.expectedBehavior')}
            name="expectedBehavior"
            onGcdsInput={handleInputChange}
            required
            textareaId="expectedBehavior"
            validateOn="submit"
            value={formData.expectedBehavior}
          />
          <GcdsTextarea
            hint={t('reportABugPage.form.systemInfoHint')}
            label={t('reportABugPage.form.systemInfo')}
            name="systemInfo"
            onGcdsInput={handleInputChange}
            required
            textareaId="systemInfo"
            validateOn="submit"
            value={formData.systemInfo}
          />
          <GcdsTextarea
            hint={t('reportABugPage.form.stepsToReproduceHint')}
            label={t('reportABugPage.form.stepsToReproduce')}
            name="stepsToReproduce"
            onGcdsInput={handleInputChange}
            required
            textareaId="stepsToReproduce"
            validateOn="submit"
            value={formData.stepsToReproduce}
          />
          <GcdsInput
            hint={t('reportABugPage.form.codeReproductionURLHint')}
            inputId="codeReproductionUrl"
            label={t('reportABugPage.form.codeReproductionURL')}
            name="codeReproductionUrl"
            onGcdsInput={handleInputChange}
            required
            type="url"
            validateOn="submit"
            value={formData.codeReproductionUrl}
          />
          <GcdsTextarea
            hint={t('reportABugPage.form.additionalInformationHint')}
            label={t('reportABugPage.form.additionalInformation')}
            name="additionalInfo"
            onGcdsInput={handleInputChange}
            textareaId="additionalInfo"
            validateOn="submit"
            value={formData.additionalInfo}
          />

          <GcdsButton type="submit">{t('reportABugPage.form.submit')}</GcdsButton>
        </form>
   </section>
      ) : (
        <div>
          <section>
              <GcdsHeading tag="h2">{t('reportABugPage.form.confirmation')}</GcdsHeading>
          <GcdsText>
            <strong>{t('reportABugPage.form.versionNumber')}:</strong> {formData.version}
          </GcdsText>
          <GcdsText>
            <strong>{t('reportABugPage.form.title')}:</strong> {formData.title}
          </GcdsText>
          <GcdsText>
            <strong>{t('reportABugPage.form.currentBehavior')}:</strong> {formData.currentBehavior}
          </GcdsText>
          <GcdsText>
            <strong>{t('reportABugPage.form.expectedBehavior')}:</strong>{' '}
            {formData.expectedBehavior}
          </GcdsText>
          <GcdsText>
            <strong>{t('reportABugPage.form.systemInfo')}:</strong> {formData.systemInfo}
          </GcdsText>
          <GcdsText>
            <strong>{t('reportABugPage.form.stepsToReproduce')}:</strong>{' '}
            {formData.stepsToReproduce}
          </GcdsText>
          <GcdsText>
            <strong>{t('reportABugPage.form.codeReproductionURL')}:</strong>{' '}
            {formData.codeReproductionUrl}
          </GcdsText>
          <GcdsText>
            <strong>{t('reportABugPage.form.additionalInformation')}:</strong>{' '}
            {formData.additionalInfo}
          </GcdsText>

          <section>
            <GcdsHeading tag="h2">{t('reportABugPage.openGithub')}</GcdsHeading>
            <GcdsButton href={buildGithubIssueUrl(formData)} target="_blank" type="link">
              {t('reportABugPage.openGithubButton')}
            </GcdsButton>
          </section>
        </div>
      )}

      <GcdsDateModified>2024-09-10</GcdsDateModified>
    </>
  )
}

// starter-apps/vue/vue-template/src/views/ReportABug.vue
<script setup>
import { useI18n } from 'vue-i18n'

import { ref } from 'vue'
import { useFormStore } from '@/stores/formStore'
import { reportABugKey } from '@/utils/refresh.js'
import Heading from '@/components/Heading.vue'
import Text from '@/components/Text.vue'
import Input from '@/components/forms/Input.vue'
import TextArea from '@/components/forms/TextArea.vue'
import Button from '@/components/forms/Button.vue'
import DateModified from '@/components/DateModified.vue'
import ErrorSummary from '@/components/forms/ErrorSummary.vue'

const { t } = useI18n()

/*
 * TODO: Add your form elements here. You may use the formElements object to store the form element IDs.
 * The v-models uses the formStore to store the form data.
 */
const formStore = useFormStore()
const formData = ref({ ...formStore.formData })
const submitted = ref(formStore.submitted)

const formElements = {
  version: 'version',
  title: 'title',
  currentBehavior: 'currentBehavior',
  expectedBehavior: 'expectedBehavior',
  systemInfo: 'systemInfo',
  stepsToReproduce: 'stepsToReproduce',
  codeReproductionUrl: 'codeReproductionUrl',
  additionalInfo: 'additionalInfo'
}

const errors = new Set();

const handleError = (key) => {
  if (key) errors.add(key);
}

const handleValid = (key) => {
  if (key) errors.delete(key);
}

async function handleSubmit(e) {
  setTimeout(() => {
    // Check if there are any errors before submitting the form
    const form = e.currentTarget;
    const hasErrors = !form.checkValidity();

    if (errors.size === 0 && !hasErrors) {
      formStore.submitForm(formData.value)
      submitted.value = formStore.submitted
    }
  }, 50)
}

// Link to the GitHub issue form with the form data pre-filled
const githubIssueURL = () => {
  const version = encodeURIComponent(formData.value.version)
  const title = encodeURIComponent(formData.value.title)
  const currentBehavior = encodeURIComponent(formData.value.currentBehavior)
  const expectedBehavior = encodeURIComponent(formData.value.expectedBehavior)
  const systemInfo = encodeURIComponent(formData.value.systemInfo)
  const stepsToReproduce = encodeURIComponent(formData.value.stepsToReproduce)
  const codeReproductionUrl = encodeURIComponent(formData.value.codeReproductionUrl)
  const additionalInfo = encodeURIComponent(formData.value.additionalInfo)

  const url =
    `https://github.com/cds-snc/gcds-components/issues/new` +
    `?=&template=bug_report.yml` +
    `&title=${title}` +
    `&package_version=${version}` +
    `&current_behavior=${currentBehavior}` +
    `&expected_behavior=${expectedBehavior}` +
    `&sys_info=${systemInfo}` +
    `&steps_to_reproduce=${stepsToReproduce}` +
    `&code_url=${codeReproductionUrl}` +
    `&more_info=${additionalInfo}`

  return url
}
</script>
<template>
  <section>
    <Heading tag="h1">{{ t('reportABugPage.heading') }}</Heading>
    <Text>{{ t('reportABugPage.intro') }}</Text>
  </section>
  <form
    v-if="!submitted"
    :key="reportABugKey"
    name="bugReportForm"
    @gcdsError="(e) => handleError(e.target.id || e.target.name)"
    @gcdsValid="(e) => handleValid(e.target.id || e.target.name)"
    @submit.prevent="(e) => handleSubmit(e)"
    novalidate
  >
    <ErrorSummary listen />
    <Input
      :id="formElements.version"
      v-model="formData.version"
      :hint="t('reportABugPage.form.versionNumberHint')"
      :label="t('reportABugPage.form.versionNumber')"
      :name="formElements.version"
      required
      validate-on="submit"
    />
    <Input
      :id="formElements.title"
      v-model="formData.title"
      :hint="t('reportABugPage.form.titleHint')"
      :label="t('reportABugPage.form.title')"
      :name="formElements.title"
      :placeholder="t('reportABugPage.form.titlePlaceholder')"
      required
      validate-on="submit"
    />
    <TextArea
      :id="formElements.currentBehavior"
      v-model="formData.currentBehavior"
      :hint="t('reportABugPage.form.currentBehaviorHint')"
      :label="t('reportABugPage.form.currentBehavior')"
      :name="formElements.currentBehavior"
      validate-on="submit"
    />
    <TextArea
      :id="formElements.expectedBehavior"
      v-model="formData.expectedBehavior"
      :hint="t('reportABugPage.form.expectedBehaviorHint')"
      :label="t('reportABugPage.form.expectedBehavior')"
      :name="formElements.expectedBehavior"
      required
      validate-on="submit"
    />
    <TextArea
      :id="formElements.systemInfo"
      v-model="formData.systemInfo"
      :hint="t('reportABugPage.form.systemInfoHint')"
      :label="t('reportABugPage.form.systemInfo')"
      :name="formElements.systemInfo"
      required
      validate-on="submit"
    />
    <TextArea
      :id="formElements.stepsToReproduce"
      v-model="formData.stepsToReproduce"
      :hint="t('reportABugPage.form.stepsToReproduceHint')"
      :label="t('reportABugPage.form.stepsToReproduce')"
      :name="formElements.stepsToReproduce"
      required
      validate-on="submit"
    />
    <Input
      :id="formElements.codeReproductionUrl"
      v-model="formData.codeReproductionUrl"
      :hint="t('reportABugPage.form.codeReproductionURLHint')"
      :label="t('reportABugPage.form.codeReproductionURL')"
      :name="formElements.codeReproductionUrl"
      required
      type="url"
      validate-on="submit"
    />
    <TextArea
      :id="formElements.additionalInfo"
      v-model="formData.additionalInfo"
      :hint="t('reportABugPage.form.additionalInformationHint')"
      :label="t('reportABugPage.form.additionalInformation')"
      :name="formElements.additionalInfo"
      validate-on="submit"
    />
    <Button type="submit">{{ t('reportABugPage.form.submit') }}</Button>
  </form>

  <div v-if="submitted">
    <Heading tag="h2">{{ t('reportABugPage.form.confirmation') }}</Heading>
    <Text>
      <strong>{{ t('reportABugPage.form.versionNumber') }}:</strong> {{ formData.version }}
    </Text>
    <Text>
      <strong>{{ t('reportABugPage.form.title') }}:</strong> {{ formData.title }}
    </Text>
    <Text>
      <strong>{{ t('reportABugPage.form.currentBehavior') }}:</strong>
      {{ formData.currentBehavior }}
    </Text>
    <Text>
      <strong>{{ t('reportABugPage.form.expectedBehavior') }}:</strong>
      {{ formData.expectedBehavior }}
    </Text>
    <Text>
      <strong>{{ t('reportABugPage.form.systemInfo') }}:</strong> {{ formData.systemInfo }}
    </Text>
    <Text>
      <strong>{{ t('reportABugPage.form.stepsToReproduce') }}:</strong>
      {{ formData.stepsToReproduce }}
    </Text>
    <Text>
      <strong>{{ t('reportABugPage.form.codeReproductionURL') }}:</strong>
      {{ formData.codeReproductionUrl }}
    </Text>
    <Text>
      <strong>{{ t('reportABugPage.form.additionalInformation') }}:</strong>
      {{ formData.additionalInfo }}
    </Text>
    <section>
      <Heading tag="h2">{{ t('reportABugPage.openGithub') }}</Heading>
      <Button :href="githubIssueURL()" target="_blank" type="link">{{
        t('reportABugPage.openGithubButton')
      }}</Button>
    </section>
  </div>
  <DateModified date="2024-09-10"></DateModified>
</template>
