// starter-apps/angular/angular-template/src/app/pages/report-a-bug/report-a-bug.component.ts
import { Component, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { GcdsComponentsModule } from '@cdssnc/gcds-components-angular';

@Component({
  selector: 'app-report-a-bug',
  imports: [GcdsComponentsModule, ReactiveFormsModule],
  templateUrl: './report-a-bug.component.html',
  styleUrl: './report-a-bug.component.scss',
})
export class ReportABugComponent {
  protected readonly submitted = signal(false);
  protected readonly issueUrl = signal(
    'https://github.com/cds-snc/gcds-components/issues/new'
  );

  protected readonly formGroup = new FormGroup({
    version: new FormControl<string | null>(null),
    title: new FormControl<string | null>(null),
    currentBehavior: new FormControl<string | null>(null),
    expectedBehavior: new FormControl<string | null>(null),
    systemInfo: new FormControl<string | null>(null),
    stepsToReproduce: new FormControl<string | null>(null),
    codeReproductionUrl: new FormControl<string | null>(null),
    additionalInfo: new FormControl<string | null>(null),
  });

  public onSubmit() {
    if (this.formGroup.valid) {
      this.submitted.set(true);
      this.issueUrl.set(
        `https://github.com/cds-snc/gcds-components/issues/new` +
          `?=&template=bug_report.yml` +
          `&title=${this.formGroup.value.title}` +
          `&package_version=${this.formGroup.value.version}` +
          `&current_behavior=${this.formGroup.value.currentBehavior}` +
          `&expected_behavior=${this.formGroup.value.expectedBehavior}` +
          `&sys_info=${this.formGroup.value.systemInfo}` +
          `&steps_to_reproduce=${this.formGroup.value.stepsToReproduce}` +
          `&code_url=${this.formGroup.value.codeReproductionUrl}` +
          `&more_info=${this.formGroup.value.additionalInfo}`
      );
    }
  }
}

<section>
  <gcds-heading tag="h1">Report a Bug</gcds-heading>
  <gcds-text>Create a report to help us improve GC Design System.</gcds-text>
</section>
@if (!submitted()) {
<form [formGroup]="formGroup" (ngSubmit)="onSubmit()">
  <gcds-input
    formControlName="version"
    label="GC Design System Components Package and Version"
    hint="e.g. @cdssnc/gcds-components-angular@0.x.x"
    [required]="true"
    validateOn="submit"
  ></gcds-input>
  <gcds-input
    formControlName="title"
    label="Title"
    hint="Choose a title for your bug report"
    [required]="true"
    validateOn="submit"
  ></gcds-input>
  <gcds-textarea
    formControlName="currentBehavior"
    label="Current Behavior"
    hint="Describe the current behavior"
    validateOn="submit"
  ></gcds-textarea>
  <gcds-textarea
    formControlName="expectedBehavior"
    label="Expected Behavior"
    hint="Describe the expected behavior"
    [required]="true"
    validateOn="submit"
  ></gcds-textarea>
  <gcds-textarea
    formControlName="systemInfo"
    label="System Info"
    hint="Provide information about your system"
    [required]="true"
    validateOn="submit"
  ></gcds-textarea>
  <gcds-textarea
    formControlName="stepsToReproduce"
    label="Steps to Reproduce"
    hint="List the steps to reproduce"
    [required]="true"
    validateOn="submit"
  ></gcds-textarea>
  <gcds-input
    formControlName="codeReproductionUrl"
    label="Code Reproduction URL"
    hint="Provide a URL to the code reproduction"
    [required]="true"
    validateOn="submit"
  ></gcds-input>
  <gcds-textarea
    formControlName="additionalInfo"
    label="Additionnal Information"
    hint="Provide any additionnal information"
    validateOn="submit"
  ></gcds-textarea>
  <gcds-button type="submit">Submit</gcds-button>
</form>
} @else {
<gcds-heading tag="h2">Confirmation</gcds-heading>
<gcds-text>
  <strong>GC Design System Components Package and Version:</strong>
  {{ formGroup.value.version }}
</gcds-text>
<gcds-text>
  <strong>Current Behavior:</strong>
  {{ formGroup.value.currentBehavior }}
</gcds-text>
<gcds-text>
  <strong>Expected Behavior:</strong>
  {{ formGroup.value.expectedBehavior }}
</gcds-text>
<gcds-text>
  <strong>System Info:</strong>
  {{ formGroup.value.systemInfo }}
</gcds-text>
<gcds-text>
  <strong>Steps to Reproduce:</strong>
  {{ formGroup.value.stepsToReproduce }}
</gcds-text>
<gcds-text>
  <strong>Code Reproduction URL:</strong>
  {{ formGroup.value.codeReproductionUrl }}
</gcds-text>
<gcds-text>
  <strong>Additional Information:</strong>
  {{ formGroup.value.additionalInfo }}
</gcds-text>
<section>
  <gcds-heading tag="h2">Start an issue on GitHub</gcds-heading>
  <gcds-link [href]="issueUrl()" target="_blank" type="link">
    Open issue on Github
  </gcds-link>
</section>
}

<gcds-date-modified>2025-07-04</gcds-date-modified>

// starter-apps/vue/vue-template/src/views/ReportABug.vue
<script setup>
import { useI18n } from 'vue-i18n'

import { ref } from 'vue'
import { useFormStore } from '@/stores/formStore'
import { reportABugKey } from '@/utils/refresh.js'
import Heading from '@/components/Heading.vue'
import Text from '@/components/Text.vue'
import Input from '@/components/forms/Input.vue'
import TextArea from '@/components/forms/TextArea.vue'
import Button from '@/components/forms/Button.vue'

const { t } = useI18n()

/*
 * TODO: Add your form elements here. You may use the formElements object to store the form element IDs.
 * The v-models uses the formStore to store the form data.
 */
const formStore = useFormStore()
const formData = ref({ ...formStore.formData })
const submitted = ref(formStore.submitted)

const formElements = {
  version: 'version',
  title: 'title',
  currentBehavior: 'currentBehavior',
  expectedBehavior: 'expectedBehavior',
  systemInfo: 'systemInfo',
  stepsToReproduce: 'stepsToReproduce',
  codeReproductionUrl: 'codeReproductionUrl',
  additionalInfo: 'additionalInfo'
}

let errors = []

const handleError = (event) => {
  if (!errors.includes(event.detail.id)) {
    errors.push(event.detail.id)
  }
}
const handleValid = (event) => {
  if (errors.includes(event.detail.id)) {
    errors = errors.filter((error) => error !== event.detail.id)
  }
}
async function handleSubmit() {
  setTimeout(() => {
    // Check if there are any errors before submitting the form
    if (errors.length === 0) {
      formStore.submitForm(formData.value)
      submitted.value = formStore.submitted
    }
  }, 50)
}

// Link to the GitHub issue form with the form data pre-filled
const githubIssueURL = () => {
  const version = encodeURIComponent(formData.value.version)
  const title = encodeURIComponent(formData.value.title)
  const currentBehavior = encodeURIComponent(formData.value.currentBehavior)
  const expectedBehavior = encodeURIComponent(formData.value.expectedBehavior)
  const systemInfo = encodeURIComponent(formData.value.systemInfo)
  const stepsToReproduce = encodeURIComponent(formData.value.stepsToReproduce)
  const codeReproductionUrl = encodeURIComponent(formData.value.codeReproductionUrl)
  const additionalInfo = encodeURIComponent(formData.value.additionalInfo)

  const url =
    `https://github.com/cds-snc/gcds-components/issues/new` +
    `?=&template=bug_report.yml` +
    `&title=${title}` +
    `&package_version=${version}` +
    `&current_behavior=${currentBehavior}` +
    `&expected_behavior=${expectedBehavior}` +
    `&sys_info=${systemInfo}` +
    `&steps_to_reproduce=${stepsToReproduce}` +
    `&code_url=${codeReproductionUrl}` +
    `&more_info=${additionalInfo}`

  return url
}
</script>
<template>
  <div>
    <section>
      <Heading class="mb-400" tag="h1">{{ t('reportABugPage.heading') }}</Heading>
      <Text>{{ t('reportABugPage.intro') }}</Text>
    </section>
    <form
      v-if="!submitted"
      :key="reportABugKey"
      name="bugReportForm"
      @gcdsError="handleError"
      @gcdsValid="handleValid"
      @submit.prevent="handleSubmit"
    >
      <Input
        :id="formElements.version"
        v-model="formData.version"
        :label="t('reportABugPage.form.versionNumber')"
        :name="formElements.version"
        required
      ></Input>
      <Input
        :id="formElements.title"
        v-model="formData.title"
        :label="t('reportABugPage.form.title')"
        :name="formElements.title"
        :placeholder="t('reportABugPage.form.titlePlaceholder')"
        required
      ></Input>
      <TextArea
        :id="formElements.currentBehavior"
        v-model="formData.currentBehavior"
        :label="t('reportABugPage.form.currentBehavior')"
        :name="formElements.currentBehavior"
      ></TextArea>
      <TextArea
        :id="formElements.expectedBehavior"
        v-model="formData.expectedBehavior"
        :label="t('reportABugPage.form.expectedBehavior')"
        :name="formElements.expectedBehavior"
        required
      ></TextArea>
      <TextArea
        :id="formElements.systemInfo"
        v-model="formData.systemInfo"
        :label="t('reportABugPage.form.systemInfo')"
        :name="formElements.systemInfo"
        required
      ></TextArea>
      <TextArea
        :id="formElements.stepsToReproduce"
        v-model="formData.stepsToReproduce"
        :label="t('reportABugPage.form.stepsToReproduce')"
        :name="formElements.stepsToReproduce"
        required
      ></TextArea>
      <Input
        :id="formElements.codeReproductionUrl"
        v-model="formData.codeReproductionUrl"
        :label="t('reportABugPage.form.codeReproductionURL')"
        :name="formElements.codeReproductionUrl"
        required
        type="url"
      ></Input>
      <TextArea
        :id="formElements.additionalInfo"
        v-model="formData.additionalInfo"
        :label="t('reportABugPage.form.additionalInformation')"
        :name="formElements.additionalInfo"
      ></TextArea>
      <Button type="submit">{{ t('reportABugPage.form.submit') }}</Button>
    </form>

    <div v-if="submitted">
      <Heading tag="h2">{{ t('reportABugPage.form.confirmation') }}</Heading>
      <Text>
        <strong>{{ t('reportABugPage.form.versionNumber') }}:</strong> {{ formData.version }}
      </Text>
      <Text>
        <strong>{{ t('reportABugPage.form.title') }}:</strong> {{ formData.title }}
      </Text>
      <Text>
        <strong>{{ t('reportABugPage.form.currentBehavior') }}:</strong>
        {{ formData.currentBehavior }}
      </Text>
      <Text>
        <strong>{{ t('reportABugPage.form.expectedBehavior') }}:</strong>
        {{ formData.expectedBehavior }}
      </Text>
      <Text>
        <strong>{{ t('reportABugPage.form.systemInfo') }}:</strong> {{ formData.systemInfo }}
      </Text>
      <Text>
        <strong>{{ t('reportABugPage.form.stepsToReproduce') }}:</strong>
        {{ formData.stepsToReproduce }}
      </Text>
      <Text>
        <strong>{{ t('reportABugPage.form.codeReproductionURL') }}:</strong>
        {{ formData.codeReproductionUrl }}
      </Text>
      <Text>
        <strong>{{ t('reportABugPage.form.additionalInformation') }}:</strong>
        {{ formData.additionalInfo }}
      </Text>
      <section>
        <Heading tag="h2">{{ t('reportABugPage.openGithub') }}</Heading>
        <Button :href="githubIssueURL()" target="_blank" type="link">{{
          t('reportABugPage.openGithubButton')
        }}</Button>
      </section>
    </div>
  </div>
</template>
